GET http://localhost:8080/api/locations

###

POST http://localhost:8080/api/locations
Content-Type: application/json

{
    "name": "VisualStudioCode",
    "coords": "10,10"
}

###
DELETE http://localhost:8080/api/locations

